"""Type stubs for python-olm (libolm Python bindings)."""

class Account:
    identity_keys: dict[str, str]
    one_time_keys: dict[str, dict[str, str]]
    fallback_key: dict[str, dict[str, str]]
    max_one_time_keys: int

    def __init__(self) -> None: ...
    def pickle(self) -> bytes: ...
    @classmethod
    def from_pickle(cls, pickle: bytes, passphrase: str = "") -> Account: ...
    def sign(self, message: bytes) -> str: ...
    def generate_one_time_keys(self, count: int) -> None: ...
    def generate_fallback_key(self) -> None: ...
    def mark_keys_as_published(self) -> None: ...

class OlmAccountError(Exception): ...
class OlmSessionError(Exception): ...
class OlmGroupSessionError(Exception): ...
class OlmVerifyError(Exception): ...

class Session:
    id: str

    def pickle(self) -> bytes: ...
    @classmethod
    def from_pickle(cls, pickle: bytes, passphrase: str = "") -> Session: ...
    def encrypt(self, plaintext: str) -> _OlmMessage: ...
    def decrypt(self, message: _OlmMessage) -> str: ...
    def matches(self, message: OlmPreKeyMessage) -> bool: ...

class _OlmMessage:
    ciphertext: str
    message_type: int
    type: int
    def __init__(self, ciphertext: str) -> None: ...

class OlmMessage(_OlmMessage): ...
class OlmPreKeyMessage(_OlmMessage): ...

class OutboundSession(Session):
    def __init__(
        self, account: Account, identity_key: str, one_time_key: str
    ) -> None: ...
    def encrypt(self, plaintext: str) -> OlmPreKeyMessage | OlmMessage: ...  # type: ignore[override]

class InboundSession(Session):
    def __init__(
        self,
        account: Account,
        message: OlmPreKeyMessage,
        identity_key: str | None = None,
    ) -> None: ...

class OutboundGroupSession:
    id: str
    session_key: str
    message_index: int

    def __init__(self) -> None: ...
    def pickle(self) -> bytes: ...
    @classmethod
    def from_pickle(
        cls, pickle: bytes, passphrase: str = ""
    ) -> OutboundGroupSession: ...
    def encrypt(self, plaintext: str) -> str: ...

class InboundGroupSession:
    id: str
    first_known_index: int

    def __init__(self, session_key: str) -> None: ...
    def pickle(self) -> bytes: ...
    @classmethod
    def from_pickle(
        cls, pickle: bytes, passphrase: str = ""
    ) -> InboundGroupSession: ...
    @classmethod
    def import_session(cls, session_key: str) -> InboundGroupSession: ...
    def decrypt(self, ciphertext: str) -> tuple[str, int]: ...
    def export_session(self, message_index: int) -> str: ...

class PkDecryption:
    public_key: str

    def __init__(self) -> None: ...
    def pickle(self) -> bytes: ...
    @classmethod
    def from_pickle(cls, pickle: bytes, passphrase: str = "") -> PkDecryption: ...

class PkMessage:
    ephemeral_key: str
    mac: str
    ciphertext: str

    def __init__(self, ephemeral_key: str, mac: str, ciphertext: str) -> None: ...

class PkEncryption:
    def __init__(self, recipient_key: str) -> None: ...

class PkSigning:
    public_key: str
    def __init__(self) -> None: ...

class Sas:
    public_key: str
    def __init__(self) -> None: ...

def sha256(message: bytes) -> bytes: ...
def ed25519_verify(key: str, message: bytes, signature: str) -> None: ...
