# This file is auto-generated by scripts/generate_client_pyi.py.
# Do not edit this file directly.
# Generated at: 2026-06-01T03:21:45Z
# Source file: nonebot/adapters/matrix/api/handle.py
# Source SHA256: 98cc9ea22e9134cf374931f8d58a1488df63d14b1853c5d306a2cd46ec8c3ab8
# Script SHA256: 23fb4be2063fea658668d0f02a4efd3a61f3e7bbff87ede267ad72504e012201

from typing import Any

from .model import (
    EventIdResponse,
    LoginFlowsResponse,
    LoginResponse,
    MediaConfigResponse,
    MembersChunkResponse,
    MessagesResponse,
    RelationsResponse,
    SyncResponse,
    UploadResponse,
    WhoamiResponse,
)
from .types import (
    EventId,
    EventType,
    ReceiptType,
    RoomIdentifier,
    TxnId,
    UserId,
)

class ApiClient:
    async def get_login_flows(
        self,
    ) -> LoginFlowsResponse:
        """Get supported Matrix login flows."""

    async def login(
        self,
        *,
        password: str,
        user: str | None = None,
        identifier: dict[str, Any] | None = None,
        device_id: str | None = None,
        initial_device_display_name: str | None = None,
        refresh_token: bool | None = None,
    ) -> LoginResponse:
        """Log in with the Matrix password flow."""

    async def logout(
        self,
    ) -> None:
        """Invalidate the current Matrix access token."""

    async def logout_all(
        self,
    ) -> None:
        """Invalidate all access tokens for the current Matrix account."""

    async def whoami(
        self,
    ) -> WhoamiResponse:
        """Return the Matrix user associated with the configured access token."""

    async def sync(
        self,
        *,
        since: str | None = None,
        timeout: int | None = None,
        filter: str | dict[str, Any] | None = None,
        full_state: bool | None = None,
        set_presence: str | None = None,
        use_state_after: bool | None = None,
    ) -> SyncResponse:
        """Long-poll Matrix sync and return room/account/ephemeral events."""

    async def send_event(
        self,
        *,
        room_id: RoomIdentifier,
        event_type: EventType,
        txn_id: TxnId,
        content: dict[str, Any],
    ) -> EventIdResponse:
        """Send a Matrix event with a client-generated transaction id."""

    async def send_message(
        self,
        *,
        room_id: RoomIdentifier,
        txn_id: TxnId,
        content: dict[str, Any],
    ) -> EventIdResponse:
        """Send an m.room.message event."""

    async def upload_content(
        self,
        *,
        content: bytes,
        filename: str | None = None,
        content_type: str | None = None,
    ) -> UploadResponse:
        """Upload bytes to the Matrix media repository and return an mxc URI."""

    async def get_media_config(
        self,
    ) -> MediaConfigResponse:
        """Get media repository limits for the homeserver."""

    async def download_media(
        self,
        *,
        server_name: str,
        media_id: str,
        filename: str | None = None,
        allow_remote: bool | None = None,
    ) -> bytes | str:
        """Download a Matrix media item."""

    async def thumbnail_media(
        self,
        *,
        server_name: str,
        media_id: str,
        width: int,
        height: int,
        method: str | None = None,
        allow_remote: bool | None = None,
    ) -> bytes | str:
        """Download a Matrix media thumbnail."""

    async def redact_event(
        self,
        *,
        room_id: RoomIdentifier,
        event_id: EventId | str,
        txn_id: TxnId,
        reason: str | None = None,
    ) -> EventIdResponse:
        """Redact a Matrix event in a room."""

    async def set_typing(
        self,
        *,
        room_id: RoomIdentifier,
        user_id: UserId | str,
        typing: bool,
        timeout: int | None = None,
    ) -> None:
        """Set the bot typing state for a room."""

    async def post_receipt(
        self,
        *,
        room_id: RoomIdentifier,
        receipt_type: ReceiptType,
        event_id: EventId | str,
        thread_id: str | None = None,
    ) -> None:
        """Post a Matrix read receipt or read marker."""

    async def get_room_members(
        self,
        *,
        room_id: RoomIdentifier,
        at: str | None = None,
        membership: str | None = None,
        not_membership: str | None = None,
    ) -> MembersChunkResponse:
        """Get membership state events for a room."""

    async def get_room_messages(
        self,
        *,
        room_id: RoomIdentifier,
        from_token: str,
        dir: str,
        to: str | None = None,
        limit: int | None = None,
        filter: str | dict[str, Any] | None = None,
    ) -> MessagesResponse:
        """Paginate Matrix room events."""

    async def get_relations(
        self,
        *,
        room_id: RoomIdentifier,
        event_id: EventId | str,
        rel_type: str | None = None,
        event_type: EventType | None = None,
        from_token: str | None = None,
        to: str | None = None,
        limit: int | None = None,
    ) -> RelationsResponse:
        """Get relation events for a Matrix event."""

    async def create_reaction(
        self,
        *,
        room_id: RoomIdentifier,
        event_id: EventId | str,
        key: str,
        txn_id: TxnId,
    ) -> EventIdResponse:
        """Send an m.reaction annotation relation."""
